---
wp_version: '5.0.3'
wp_install_dir: "/var/www/{{ wp_sitename }}"
wp_sitename: html
wp_db_collate: ''
wp_apache_port: 9000

wp_debug: false
wp_admin_email: 'admin@example.com'
site_name: "{{ wp_sitename }}"

# WP SQL Config
wp_db_host: '172.20.0.3'
wp_db_name: wordpress
wp_db_user: vagrant
wp_db_password: vagrant12345
wp_db_charset: 'utf8'
wp_table_prefix: 'wp_'