- import_tasks: check_vars.yml

- name: include vars
  include_vars: "./vars/main.yml"

- name: install nginx
  become: yes
  apt:
    force_apt_get: yes
    name: ["nginx"]
    update_cache: yes

- name: setup nginx reverse proxy
  become: yes
  template:
    src: templates/nginx.j2
    dest: /etc/nginx/sites-available/{{ reverse_proxy_site_name }}
  notify:
    - test nginx configuration

- name: put reverse proxy site config in enabled
  become: yes
  file:
    src: /etc/nginx/sites-available/{{ reverse_proxy_site_name }}
    dest: /etc/nginx/sites-enabled/{{ reverse_proxy_site_name }}
    state: link

- name: reload nginx service
  become: yes
  service:
    name: nginx
    state: reloaded
    enabled: yes